
const KEY="gbme365-auto-v4";const $=s=>document.querySelector(s);
const state=JSON.parse(localStorage.getItem(KEY)||'{"done":{},"starred":{}}');let page="today",manualDay=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dateISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function dayFromDate(){const s=new Date(GBME_CONTENT.meta.startDate+"T00:00:00"),n=new Date(dateISO()+"T00:00:00");return Math.max(1,Math.min(365,Math.floor((n-s)/86400000)+1))}
function currentDay(){return manualDay||dayFromDate()} function getDay(n){return GBME_CONTENT.days.find(d=>d.day===n)}
function maxLoaded(){return Math.max(...GBME_CONTENT.days.map(d=>d.day))} function clamp(n){return Math.max(1,Math.min(maxLoaded(),n))}
function allSentences(){return GBME_CONTENT.days.flatMap(d=>(d.sentences||[]).map(s=>({...s,day:d.day})))}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toggleDone(id){state.done[id]=!state.done[id];save();render()} function toggleStar(id){state.starred[id]=!state.starred[id];save();render()}
function speak(text){if(!("speechSynthesis" in window)){alert("이 브라우저에서는 TTS를 지원하지 않아요.");return}const syn=speechSynthesis;syn.cancel();syn.resume();const u=new SpeechSynthesisUtterance(text),vs=syn.getVoices()||[],v=vs.find(v=>/Samantha|Ava|Allison|Susan/i.test(v.name))||vs.find(v=>v.lang==="en-US")||vs.find(v=>/^en/i.test(v.lang));if(v)u.voice=v;u.lang="en-US";u.rate=.88;u.volume=1;u.onerror=()=>alert("TTS 재생이 제한됐어요. 아래 오디오 테스트를 먼저 확인해 주세요.");setTimeout(()=>syn.speak(u),60)}
function audioTest(){try{const A=window.AudioContext||window.webkitAudioContext,c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=720;g.gain.setValueAtTime(.18,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.3);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.3)}catch(e){alert("오디오 테스트 실행 실패")}}
function card(s){const d=!!state.done[s.id],st=!!state.starred[s.id];return `<div class="card ${d?"done":""}"><div class="label">Day ${s.day}</div><div class="sentence">${esc(s.text)}</div><div class="meaning">${esc(s.meaning)}</div><div>${(s.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join("")}</div><div class="actions"><button class="btn ${d?"good":""}" onclick="toggleDone('${s.id}')">${d?"✓ 외움":"외웠어요"}</button><button class="btn ${st?"star":""}" onclick="toggleStar('${s.id}')">${st?"★ 저장됨":"☆ 즐겨찾기"}</button><button class="btn" onclick='speak(${JSON.stringify(s.text)})'>🔊 듣기</button></div></div>`}
function wordCard(w){return `<div class="card"><div class="word">${esc(w.word)}</div><div class="wordmeaning">${esc(w.meaning)}</div><div class="example">${esc(w.example)}</div><div class="actions"><button class="btn" onclick='speak(${JSON.stringify(w.word)})'>🔊 듣기</button></div></div>`}
function navDay(){return `<div class="navday"><button onclick="moveDay(-1)">← 이전</button><button class="today" onclick="goToday()">Today · Day ${dayFromDate()}</button><button onclick="moveDay(1)">다음 →</button></div>`}
function moveDay(x){manualDay=clamp(currentDay()+x);page="today";render()}function goToday(){manualDay=null;page="today";render()}function jumpDay(n){manualDay=n;page="today";render()}
function learn(d){return `<section class="section"><div class="sectionhead"><h3>필수 문장</h3><span>2 sentences</span></div><div class="grid">${d.sentences.map(s=>card({...s,day:d.day})).join("")}</div></section><section class="section"><div class="sectionhead"><h3>오늘의 단어</h3><span>5 words</span></div><div class="grid two">${d.words.map(wordCard).join("")}</div></section>`}
function reviewSec(d){const from=Math.max(1,d.day-4),to=d.day-1,ss=allSentences().filter(s=>s.day>=from&&s.day<=to);return `<section class="section"><div class="sectionhead"><h3>오늘은 새 학습 없음</h3><span>Day ${from}–${to}</span></div><div class="reviewBox">${d.reviewTasks.map((t,i)=>`<div class="reviewTask"><b>${i+1}. Review Mission</b>${esc(t)}</div>`).join("")}</div></section><section class="section"><div class="sectionhead"><h3>복습 문장</h3><span>${ss.length} sentences</span></div><div class="grid">${ss.map(card).join("")}</div></section>`}
function todayPage(){const n=currentDay(),d=getDay(n);if(!d)return `${navDay()}<div class="card empty"><b>Day ${n}</b><br><br>아직 이 Day 콘텐츠가 추가되지 않았어요.<br>현재는 Day 1–10까지 들어 있습니다.</div>`;const r=d.type==="review",done=(d.sentences||[]).filter(s=>state.done[s.id]).length;return `${navDay()}<div class="hero ${r?"review":""}"><div class="kicker">${r?"REVIEW DAY":"TODAY'S LESSON"} · DAY ${d.day}</div><h2>${esc(d.focus)}</h2><p>${esc(d.mission)}</p><div class="stats"><div class="stat"><b>${r?"0":(d.sentences||[]).length}</b><span>새 문장</span></div><div class="stat"><b>${r?"복습":done+"/"+(d.sentences||[]).length}</b><span>${r?"오늘 목표":"완료"}</span></div><div class="stat"><b>${d.day%5===0?"★":"●"}</b><span>${d.day%5===0?"5일 복습":"학습일"}</span></div></div></div>${r?reviewSec(d):learn(d)}<section class="section"><div class="card"><div class="label">Audio check</div><div class="sentence" style="font-size:17px">소리가 안 날 때 테스트</div><div class="meaning">테스트음이 들리면 iPhone 출력은 정상이고 TTS만 제한된 상태입니다.</div><div class="actions"><button class="btn primary" onclick="audioTest()">🔈 오디오 테스트</button></div></div></section>`}
function libraryPage(){return `<div class="sectionhead"><h3>Library</h3><span>Day 바로가기</span></div><div class="dayjump">${GBME_CONTENT.days.map(d=>`<button class="${currentDay()===d.day?"active":""}" onclick="jumpDay(${d.day})">${d.type==="review"?"🔁 ":""}Day ${d.day}</button>`).join("")}</div><input id="q" class="search" placeholder="문장·뜻·태그 검색" oninput="filterLibrary()"><div id="lib"></div>`}
function filterLibrary(){const q=($("#q")?.value||"").toLowerCase(),list=allSentences().filter(s=>(s.text+" "+s.meaning+" "+(s.tags||[]).join(" ")).toLowerCase().includes(q));$("#lib").innerHTML=list.length?`<div class="grid">${list.map(card).join("")}</div>`:`<div class="empty">검색 결과가 없어요.</div>`}
function reviewPage(){const a=allSentences(),st=a.filter(s=>state.starred[s.id]),nd=a.filter(s=>!state.done[s.id]).slice(0,8);return `<div class="sectionhead"><h3>Quick Review</h3><span>즐겨찾기 우선</span></div>${st.length?`<div class="grid">${st.map(card).join("")}</div>`:`<div class="card empty">즐겨찾기한 문장이 아직 없어요.</div>`}<section class="section"><div class="sectionhead"><h3>아직 안 외운 문장</h3><span>최대 8개</span></div><div class="grid">${nd.map(card).join("")}</div></section>`}
function infoPage(){return `<div class="card"><div class="label">Automatic Day</div><div class="sentence" style="font-size:18px">오늘은 자동으로 Day ${dayFromDate()}</div><div class="meaning">2026-08-07을 Day 1로 잡아 날짜가 바뀌면 Day도 자동으로 증가합니다. Day 5, 10, 15…는 복습 전용일입니다.</div></div><section class="section"><div class="card"><div class="label">Content status</div><div class="sentence" style="font-size:18px">현재 Day 1–10 탑재</div><div class="meaning">Day 11부터는 content.js만 업데이트하면 됩니다.</div></div></section>`}
function go(p){page=p;render()}function tabs(){return `<nav class="tabs">${[["today","Today"],["library","Library"],["review","Review"],["info","Info"]].map(([p,l])=>`<button class="tab ${page===p?"active":""}" onclick="go('${p}')">${l}</button>`).join("")}</nav>`}
function render(){const body=page==="today"?todayPage():page==="library"?libraryPage():page==="review"?reviewPage():infoPage();$("#app").innerHTML=`<div class="app"><header class="top"><div class="brand"><h1>영어마스터 365</h1><p>나도 할 수 있다 · English for Work · Every Day</p></div><div class="pill">Day ${currentDay()}</div></header>${body}</div>${tabs()}`;if(page==="library")filterLibrary()}
if("speechSynthesis" in window){speechSynthesis.getVoices();speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices()}if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}))}render();
